update

diff --git a/.github/workflows/build-docker-image.yml b/.github/workflows/build-docker-image.yml
--- a/.github/workflows/build-docker-image.yml
+++ b/.github/workflows/build-docker-image.yml
@@ -30,16 +30,11 @@ jobs:
         echo "CI_COMMIT_MESSAGE=$CI_COMMIT_MESSAGE" >> $GITHUB_ENV
         echo "CI_COMMIT_BRANCH=$CI_COMMIT_BRANCH" >> $GITHUB_ENV
         echo "CI_COMMIT_SHA=${{ github.event.head_commit.id }}" >> $GITHUB_ENV
-        echo "IMAGE_TAG_LATEST=lswl/vertex:latest" >> $GITHUB_ENV
+        echo "IMAGE_TAG_LATEST=akafra/vertex:latest" >> $GITHUB_ENV
         echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
-        echo "IMAGE_TAG_BRANCH=lswl/vertex:$CI_COMMIT_BRANCH" >> $GITHUB_ENV
+        echo "IMAGE_TAG_BRANCH=akafra/vertex:$CI_COMMIT_BRANCH" >> $GITHUB_ENV
         echo "PUSH_TIME=$PUSH_TIME" >> $GITHUB_ENV
         echo "KEY=$KEY" >> $GITHUB_ENV
-    - name: Push Start Message
-      run: |
-        curl --location --request POST 'https://vertex-push.lswl.workers.dev' \
-          --header 'Content-Type: application/json' \
-          --data-raw "{\"key\": \"$KEY\",\"time\": \"$PUSH_TIME\",\"message\": \"$CI_COMMIT_MESSAGE\",\"branch\": \"$CI_COMMIT_BRANCH\",\"sha1\": \"${CI_COMMIT_SHA:0:12}\", \"type\": \"start\"}"
     - name: Install Dependencies
       run: |
         npm i --save-dev
@@ -89,13 +84,13 @@ jobs:
         cd docker
         sed -i 's/COMMIT_ID/'$CI_COMMIT_SHA'/' Dockerfile
         ls src/static
-        docker pull --platform linux/arm64 lswl/vertex:latest || echo 'fail'
-        docker pull --platform linux/amd64 lswl/vertex:latest || echo 'fail'
+        docker pull --platform linux/arm64 akafra/vertex:latest || echo 'fail'
+        docker pull --platform linux/amd64 akafra/vertex:latest || echo 'fail'
     - name: Build Docker Images
       working-directory: ./docker
       run: |
-        docker buildx build --platform linux/amd64,linux/arm64 --cache-from lswl/vertex --tag $IMAGE_TAG_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 . --push
-        docker buildx build --platform linux/amd64,linux/arm64 --cache-from lswl/vertex --tag $IMAGE_TAG_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 . --push
+        docker buildx build --platform linux/amd64,linux/arm64 --cache-from akafra/vertex --tag $IMAGE_TAG_LATEST --build-arg BUILDKIT_INLINE_CACHE=1 . --push
+        docker buildx build --platform linux/amd64,linux/arm64 --cache-from akafra/vertex --tag $IMAGE_TAG_BRANCH --build-arg BUILDKIT_INLINE_CACHE=1 . --push
     - name: Push Finish Message
       run: |
         curl --location --request POST 'https://vertex-push.lswl.workers.dev' \
